### ISSUE TITLE
gem installation error, "server did not return a valid file"

### ISSUE THREAD

**Issue by irons** [firmafon/ruby-fogbugz#13]
Any thoughts on this installation error?

```
$ gem install ruby-fogbugz
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    server did not return a valid file (https://api.rubygems.org/api/v1/dependencies?gems=ruby-fogbugz)
```

I get the same error when I try installing a locally-built version of the gem. I'm not sure how to troubleshoot the file at that URL, the contents of which are [available here](https://gist.github.com/irons/d2558487c193f1249d3a). I'm using ruby 2.1.5 with rbenv. Thanks for your time.

**Comment by szechyjs** [comment]
this looks like an issue with rubygems. is this still an issue?

**Comment by nonnenmacher** [comment]
yes, this is still an issue.

**Comment by nonnenmacher** [comment]
My fault, the answer is that ; 'you need to update your ruby gem' (you could add 'stupid' here !)

So the answer is 
 ` gem update --system`
 and all is fine afterward. Sorry for this
